[module]
  [module.hugoVersion]
    extended = true
    min = "0.140.0"

[outputs]
  _merge = 'deep'
[cascade]
  _merge = 'deep'

[markup.goldmark.renderer]
  unsafe = true

[outputformats]
  _merge = 'deep'
[outputFormats.search]
  baseName = "search"
  mediaType = "application/json"
  isPlainText = true
  notAlternative = false

[[redirects]]  # Default lang, should be last.
from = '/**'
to = '/404.html'
status = 404  